// Planned slots are not unlock rules. Missing candidates stay explicit.
const slot=(title:string,sourceId:string|null,note:string)=>({title,sourceId,note});
export const CAMPAIGN_PLAN=[
 {name:'UltraOx Dual',levelIndex:0,slots:[slot('Warm / cool introduction','courses-3-0-1254228653','Candidate opener: a restrained warm mixture, not yet player-approved.'),slot('Setup into a lift','courses-3-0-2047564836','Lift opportunity from chromatic starts; white can take a simpler route. Test that tradeoff.'),slot('Blue finish','lab-7-0-0-33f2ab72f2c7','Known positive alternate-start route. Compare its feel with the lift slot.')]},
 {name:'Maroon Drift',levelIndex:25,slots:[slot('Gentle mixing','lab-8-25-0-08478f9bff37','Beginner candidate: judge satisfying simplicity, not just low difficulty.'),slot('Simple chromatic contrast',null,'Find a second satisfying, readable hole rather than a near-duplicate.')]},
 {name:'Zorny',levelIndex:1,slots:[slot('Warm nuance','lab-2-1-250769685','Known positive warm route.'),slot('Cool direction using black',null,'Find a cool chromatic target without a trivial white/black-axis route.'),slot('Setup and value','lab-4-1-1024-test','Positive lift review; old audit left one base unresolved. Recheck in play.'),slot('Demanding cool finish',null,'Select a stronger cooler finish; old cool targets were not uniformly satisfying.')]},
 {name:'RYB',levelIndex:2,slots:[slot('Chromatic approach','lab-6-2-1-8d07d75b36d8','Kept, but nearby red start is gentler.'),slot('Cool-color contrast',null,'Needs a worthwhile cool target.'),slot('Darker mixture',null,'Needs a distinct dark mixing problem.'),slot('Broad mixing finish','lab-7-2-0-9622ba700144','Known positive multi-start, three-addition setup benchmark.')]},
 {name:'Orange Echo',levelIndex:17,slots:[slot('Warm mixing','lab-5-17-0-f0cef0969c87','Known positive warm route.'),slot('Dark contrast','lab-5-17-1-b46b6def6b93','Kept as an easier dark route, not demanding balancing.'),slot('Best balancing finish',null,'Seek a harder neutral or balancing finish worth taking from different bases.')]},
 {name:'CMY',levelIndex:4,slots:[slot('Chromatic ride','lab-3-4-946301308','Earlier positive alternate-start ride. Check current timing feel.'),slot('Contrasting precise ride',null,'Needs a different hue family and worthwhile shortest alternatives.')]},
 {name:'Secondaries',levelIndex:5,slots:[slot('Multi-approach setup','courses-2-5-3268230473','Known positive approaches from several starts.'),slot('Green setup','courses-2-5-3500426429','Positive setup and separation; needs broader start testing.'),slot('Coupled balance','lab-4-5-11-test','Positive coupled-balance benchmark.'),slot('Demanding multi-pour finish','lab-3-5-2417069514','One of the strongest difficult-setup reviews. Preserve optional starting paints.')]},
 {name:'Sienna Field',levelIndex:29,slots:[slot('Restricted mixing','lab-9-29-0-b83acde81b54','Interesting compact route; not inherently a required value lift.'),slot('Precise contrasting finish',null,'Find a different restricted-gamut problem; it need not just be more neutral.')]},
 {name:'Maroon Arc',levelIndex:30,slots:[slot('Expansive green ride','lab-9-30-0-3baaea8d7013','All four starts played; judge the different experiences, not identical difficulty.'),slot('Warm or dark counterpart',null,'Find a different destination and approach.'),slot('Precise ending',null,'Needs a satisfying efficient route before any stricter par gate.')]},
 {name:'Teal Ember',levelIndex:24,slots:[slot('Off-center introduction',null,'Find a distinct introduction to lateral/inward mixing.'),slot('Inward setup','lab-9-24-0-5e2d38157f76','Repeated positive reference; try more bases as well as the known magenta start.')]},
 {name:'French Light',levelIndex:6,slots:[slot('Broad-choice studio puzzle',null,'One hole: test economical paint choice without forcing a restricted-palette style.')]},
 {name:'Cobalt Ember',levelIndex:10,slots:[slot('Readable introduction',null,'Find an opener unlike the later neutral setups.'),slot('Accurate ride','lab-7-10-1-835415fde974','Known positive ride and alternatives; candidate precision benchmark.'),slot('Rose-gray setup','lab-3-10-3771051873','Positive setup reference; compare against the finale for repetition.'),slot('Demanding interior finale','lab-7-10-0-17677c256f07','Known challenging all-base sampled three-addition benchmark.')]},
];
