'use client';
import {useState} from 'react';
import {PLAY_LEVELS,mixtureColor,rgbStyle,colorDistance,pourPath,type ColorPoint} from './play-engine';
import {premixRoute,type MassMode} from './play-premix';
import {premixBank,regionBank,legLabBank,branchLabBank,conditionedLabBank,workbenchBank,generatePremixHole,premixItem,type PremixRow} from './play-premix-bank';
import type {LabSpecimen,LabEntry} from './play-lab-model';
import {routeGraphBounds} from './play-lab-graph';
const labels:Record<string,string>={rise:'Setup → value rise',drop:'Setup → value drop','coupled-balance':'Coupled balance','long-finish':'Setup → long chromatic finish','chromatic-ride':'Chromatic ride','setup-glide':'Setup → glide','interior-assembly':'Interior assembly'};
export function PremixPicker({current,onChoose,archive=false,collection='regions',items}:{current:LabSpecimen;onChoose:(s:LabSpecimen)=>void;archive?:boolean;collection?:'regions'|'legs'|'branches'|'conditioned'|'workbench';items?:PremixRow[]}){
 const rows:PremixRow[]=items??(archive?premixBank.holes:collection==='workbench'?workbenchBank.holes:collection==='conditioned'?conditionedLabBank.holes:collection==='branches'?branchLabBank.holes:collection==='legs'?legLabBank.holes:regionBank.holes);
 const active=rows.find(h=>h.id===current.hole.premix?.pairId),item=active??rows[0],mode:MassMode=archive?(current.hole.premix?.massMode??'normalized'):'normalized';
 const choose=(id:string,m:MassMode)=>{const row=rows.find(h=>h.id===id)!;onChoose({levelIndex:row.level,hole:generatePremixHole(id,m)});};
 if(!rows.length)return <p>No specimens in this collection yet.</p>;
 return <><label>{collection==='workbench'?'Hole in this selection':'Premix puzzle'}<select value={active?.id??''} onChange={e=>choose(e.target.value,mode)}>{!active&&<option value="">Choose a puzzle…</option>}{rows.map((h,i)=><option key={h.id} value={h.id}>{i+1}. {PLAY_LEVELS[h.level].name} · {h.title??labels[h.style]}{h.role?.startsWith('reference')?' · Familiar reference':''}</option>)}</select></label>
 {archive&&<label>Quantity behavior<select value={mode} onChange={e=>choose(item.id,e.target.value as MassMode)}><option value="accumulated">A · Archived accumulated mass</option><option value="normalized">B · Normalize to 1 part</option></select></label>}
 <button type="button" onClick={()=>choose(item.id,mode)}>{active?'Replay this version':item.freeBase?'Start free-base hole':'Start premix puzzle'}</button>
 {active&&archive&&<button type="button" onClick={()=>choose(item.id,mode==='accumulated'?'normalized':'accumulated')}>Replay same puzzle in {mode==='accumulated'?'B':'A'} →</button>}
 {!archive&&active&&<button type="button" onClick={()=>choose(rows[(rows.indexOf(item)+1)%rows.length].id,'normalized')}>Next puzzle →</button>}
 <p className="lab-muted">{archive?'Archived A/B comparison.':collection==='workbench'?'Course workbench: six premix discoveries and six normalized free-base versions of campaign targets. Pigment strengths and landing tolerance unchanged.':collection==='conditioned'?'Sixteen newly playable puzzles from the earlier destination-conditioned bank: twelve shortest-found three-leg cases and four deliberate two-leg contrasts. Light, dark and chromatic targets, including a shared destination across three palettes. This is separate from the new region-branching comparison. Normalized mass; pigment strengths unchanged.':collection==='branches'?'Four three-leg setups, each with two refined branches to compare. Try naturally first; replay with another first pigment if useful. Normalized mass; pigment strengths unchanged.':collection==='legs'?'Ten contrasting puzzles: setups, rides, value shifts, a Zorn reference and two longer-route explorations. Normalized mass; pigment strengths unchanged.':'Nine new puzzles and two familiar references. Normalized mass throughout; pigment strengths unchanged.'} {item.freeBase?'Choose any base for free; quantity resets to 1 part after every later pour.':'Every pour counts; no free base choice.'} Par 3 is held constant, not a newly calibrated difficulty score. Labels describe candidate experiences, not guaranteed enjoyment.</p>
 {!archive&&active&&(collection==='workbench'?<details><summary>Hole brief &amp; checked alternatives</summary><RegionEvidence item={item}/></details>:<RegionEvidence item={item}/>)}
 {!item.freeBase&&<details><summary>Prepared mixture · 1 part at start</summary><div className="lab-route-stops">{item.initial.map((q,i)=><div key={i}><i style={{background:rgbStyle(PLAY_LEVELS[item.level].paints[i].rgb)}}/><span>{PLAY_LEVELS[item.level].paints[i].name}<strong>{(q*100).toFixed(1)}%</strong></span></div>)}</div><p>Normalized mode preserves pigment proportions and resets total quantity to 1 after each shot. Archived A keeps accumulated quantities.</p></details>}</>;
}
export function CourseWorkbenchPicker(props:{current:LabSpecimen;onChoose:(s:LabSpecimen)=>void}){
 const current=premixItem(props.current.hole),[track,setTrack]=useState(current?.freeBase?'free':'premix'),[palette,setPalette]=useState('all');
 const trackRows=workbenchBank.holes.filter(h=>Boolean(h.freeBase)===(track==='free')),levels=[...new Set(trackRows.map(h=>h.level))],rows=trackRows.filter(h=>palette==='all'||h.level===Number(palette));
 return <><label>Testing track<select value={track} onChange={e=>{setTrack(e.target.value);setPalette('all');}}><option value="premix">Six new premix discoveries</option><option value="free">Free-base · three two-hole sequences</option></select></label><label>Palette<select value={palette} onChange={e=>setPalette(e.target.value)}><option value="all">All palettes in this track</option>{levels.map(i=><option key={i} value={i}>{PLAY_LEVELS[i].name}</option>)}</select></label>
 <PremixPicker key={`${track}-${palette}`} collection="workbench" items={rows} {...props}/>
 <button type="button" onClick={()=>{const r=branchLabBank.holes[0];props.onChoose({levelIndex:r.level,hole:generatePremixHole(r.id,'normalized')});}}>Replay earlier Hansa branching favorite</button>
 <details className="lab-course-board"><summary>Palette &amp; course board · {workbenchBank.board.length} palettes</summary><p>Provisional evidence, not a ranking. Original campaign plans remain intact. A screen count is not a count of player-approved holes; no result is not a rejection.</p>{workbenchBank.board.map(p=><article key={p.name}><h3>{p.name}</h3><p>{p.paints.join(' · ')}</p><p><strong>{p.status}</strong> · {p.targets} targets examined · {p.freeNontrivial} nontrivial free-base candidates · {p.premixCandidates} new premix nominations</p><p>{p.note}</p>{p.playable.map(id=>{const h=workbenchBank.holes.find(h=>h.id===id)!;return <button key={id} type="button" onClick={()=>{setTrack(h.freeBase?'free':'premix');setPalette(String(h.level));props.onChoose({levelIndex:h.level,hole:generatePremixHole(id,'normalized')});}}>{h.freeBase?'Free-base':'Premix'} · {h.title}</button>;})}</article>)}</details></>;
}
function RegionEvidence({item}:{item:PremixRow}){
 if(item.lab)return <div className="lab-muted"><p><strong>{item.title} · {labels[item.style]}</strong></p><p>{item.lab.brief}</p><p>{item.lab.rawLegMinimum} pigment legs: shortest found · {item.lab.regionLegMinimum??'unconfirmed'}: proportion-supported shortest. {item.lab.exploratory?`The featured ${item.lab.featuredLegs}-leg journey is not necessary to win.`:'Different efficient orders may feel different.'} A leg means consecutive use of one pigment, even across several releases. These are bounded search findings, not proofs.</p></div>;
 const c=item.classification;if(!c)return null;
 if(item.role?.startsWith('reference'))return <p>Familiar reference · {item.role==='reference-easy'?'Previously felt too easy.':'Previously enjoyed.'} Included for comparison, not presented as a newly validated finalist.</p>;
 return <div className="lab-muted"><p><strong>{c.rawMinimum} additions: shortest found · {c.timingMinimum??'none'}: timing-supported shortest.</strong></p><p>{c.status==='required-in-tested-routes'?'No efficient style bypass found in this bounded search.':c.status==='competitive'?'The intended style is competitive, but equally short alternatives can feel different.':'The intended style is available; a more efficient approach can bypass it.'} These are search findings, not proofs.</p></div>;
}
export function PremixRouteReview({entry}:{entry:LabEntry}){
 const {attempt}=entry,hole=attempt.specimen.hole,premix=hole.premix!,item=premixItem(hole)!,paints=PLAY_LEVELS[attempt.specimen.levelIndex].paints;
 const [shown,setShown]=useState(true),[example,setExample]=useState(-1);
 const evidence=item.modes[premix.massMode]!,r=example<0?evidence.measurement:evidence.rivals[example]??evidence.measurement;
 const fullSolution=premixRoute(paints,premix.initial,r.order,r.times,premix.massMode,premix.freeBase),solution=premix.freeBase?{...fullSolution,path:fullSolution.path.slice(1),stops:fullSolution.stops.slice(1)}:fullSolution;
 const paths=attempt.shots.filter(s=>!s.cancelled).map(s=>pourPath(paints,s.before,s.paint,s.amount,64));
 const allRecorded=attempt.shots.filter(s=>!s.cancelled),recorded=premix.freeBase?allRecorded.slice(1):allRecorded,recordedLegs=recorded.filter((s,i)=>!i||s.paint!==recorded[i-1].paint).length;
 const bounds=routeGraphBounds(paths.flat(),[],solution.path,hole.target);
 const project=(p:ColorPoint,axes:[number,number])=>axes.map((axis,i)=>{const [min,max]=bounds[axis],t=(p.position[axis]-min)/Math.max(1,max-min);return i?150-t*130:15+t*270;});
 return <div className="lab-route"><p><strong>{labels[item.style]??item.style} · {premix.massMode==='accumulated'?'Archived accumulated':'Normalized'}</strong>. {premix.freeBase?'Free base selection; examples may start with different paints. The first selection is not a counted pour.':'The starting recipe is fixed; all recorded actions count.'}</p><RegionEvidence item={item}/>
 <div className="lab-maps">{([[0,2],[0,1]] as [number,number][]).map((axes,i)=><figure key={i}><figcaption>{i?'Side · value':'Above · hue/chroma'}</figcaption><svg viewBox="0 0 300 170" role="img" aria-label="Premix route comparison">{[...(shown?[solution.path]:[]),...paths].map((path,j)=><g key={j}>{path.slice(1).map((p,k)=>{const a=project(path[k],axes),b=project(p,axes);return <line key={k} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} stroke={rgbStyle(p.rgb)} strokeWidth={shown&&j===0?5:2}/>;})}</g>)}{[solution.stops[0],hole.target].map((p,j)=>{const [x,y]=project(p,axes);return <circle key={j} cx={x} cy={y} r={j?7:5} fill={rgbStyle(p.rgb)} stroke="white"/>;})}</svg></figure>)}</div>
 <button type="button" onClick={()=>setShown(!shown)}>{shown?'Hide':'Show'} example</button>
 {item.lab&&<p>Your route: {recordedLegs} pigment legs · {recorded.length} releases.</p>}
 {shown&&<><label>Compare {premix.freeBase?'starting paints and routes':'routes from this premix'}<select value={example} onChange={e=>setExample(Number(e.target.value))}><option value={-1}>{item.lab?'Featured example':'Backward-planned finish'}</option>{evidence.rivals.map((r,i)=><option key={i} value={i}>{r.label?`${r.label} · `:''}{r.order.map(p=>paints[p].name).join(' → ')} · {item.lab?(r.proportionSupported?'proportion-supported':'raw endpoint'):(r.supported?'timing-supported':'raw endpoint')}</option>)}</select></label><div className="lab-route-stops">{solution.stops.map((p,i)=><div key={i}><i style={{background:rgbStyle(p.rgb)}}/><span>{i||premix.freeBase?paints[r.order[i-(premix.freeBase?0:1)]].name:'Prepared mixture'}<strong>{i?`${r.times[i-(premix.freeBase?0:1)].toFixed(3)} s`:premix.freeBase?'Free base':'Start'}</strong></span></div>)}</div>{item.collection==='public'?<p>{r.times.length} releases in this example. Times shown are legacy-equivalent replay controls, not required hold times for the new touch response. Live timing difficulty has not been calibrated; the starting recipe and target are unchanged.</p>:item.lab?<p>{r.legCount} pigment legs · {r.times.length-(premix.freeBase?1:0)} counted releases in this example · {Math.round(r.finishWindowMs)} ms local final-release window. Connected finishing-leg fraction window: {((r.finishShareWidth??0)*100).toFixed(1)} percentage points; {(r.setupCoverage*100).toFixed(0)}% sampled local setup-fraction coverage. Timing and fraction support are different measurements, not success odds.</p>:<p>{r.times.length} additions · {Math.round(r.finishWindowMs)} ms sampled finish window · {(r.setupCoverage*100).toFixed(0)}% local setup slice. {item.role?'The window contains this example’s release; the setup slice perturbs all setup controls and re-searches the finish.':'Archived widest-window / first-setup measurement.'} Approximate—not success odds or a global region size.</p>}</>}
 {item.lab&&<details><summary>Selection evidence</summary><p>{item.lab.method==='normalized-free-base'?'Original campaign target revalidated from every pure base using normalized quantity. Base selection is free; subsequent pigment legs and releases are measured separately.':item.lab.method==='hybrid-exclusion'?'Fresh palette/start/target proposals, screened against shorter alternatives and independently checked again before release.':item.lab.method==='exclusion-bank'?'Previously banked numerical finalist, independently rechecked and made playable here for the first time.':item.lab.method==='destination-conditioned'?'Earlier destination-conditioned proposal/refinement, with a fresh independent shortcut check before lab release. Target request and observed finishing style are kept separate.':item.lab.method==='branch-refined'?'Shared start and two branches refined together; target and pigments held fixed.':item.lab.method==='reference'?'Familiar player-reviewed reference.':`${item.lab.method==='route-first'?'Route-first':'Palette-first'} proposal; curated for this collection.`} Style evidence: {item.lab.styleStatus.replaceAll('-',' ')}. This describes sampled alternatives, not a required style.</p><p>Source: {item.lab.sourceId}</p></details>}
 <p className="lab-muted">Thick line: selected example. Thin lines: your pours. Saved attempts keep their original quantity mode and target.</p></div>;
}
